- name: reboot Junos devices
  hosts: EX4300
  connection: local
  gather_facts: no
  
  roles:
    - Juniper.junos

  tasks:

    - name: reboot Junos devices
      juniper_junos_system:
          provider: "{{ credentials }}"
          action: "reboot"

