---
loopback: 192.179.0.73
local_asn: 110
neighbors:
   - interface: ge-0/0/0
     name: ex4300-9
     asn: 109
     peer_ip: 192.168.0.5 
     local_ip: 192.168.0.4
     peer_loopback: 192.179.0.95
   - interface: ge-0/0/1 
     name: ex4300-18
     asn: 104
     peer_ip: 192.168.0.3
     local_ip: 192.168.0.2 
     peer_loopback: 192.179.0.74

